[package]
name = "discord-lsp-presence"
version = "0.1.0"
edition = "2024"

[dependencies]
discord-presence = "3.2.0"
tower-lsp = "0.20.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
